# Specify the version of the docker-compose file format
version: '3.8' 

# Define the services
services: 

  # PHP service
  php: 
    # Use the Dockerfile in the current directory to build the image
    build:
      context: .
      target: app_php
    restart: on-failure

    # Name of the container
    container_name: blog_api_php 

    env_file:
      - .env.local

    # Mount the application directory into the container
    volumes: 
      - .:/var/www/html:rw,cached

    # Set the application environment to development
    environment: 
      - APP_ENV=dev
      - APP_DEBUG=1
      - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
      - DATABASE_URL=${DATABASE_URL}
      # - PHP_MEMORY_LIMIT=512M


    # Ensure the db service is started before PHP
    depends_on:
      database:
        condition: service_healthy
    
    # entrypoint: /usr/local/bin/docker-entrypoint

  # Adminer service
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # Nginx service
  nginx: 
    build:
      context: .
      target: nginx_app
    # Name of the container
    container_name: blog_api_nginx

    # Map port 80 of the container to port 8000 on the host 
    ports: 
      - "8000:80"
    
    # Mount the application directory and Nginx configuration file into the container
    volumes: 
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/nginx.conf:ro

    # Ensure the PHP and db services are started before Nginx
    depends_on: 
      - php
      - database
        


###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    restart: on-failure
    environment:
      # You should definitely change the password in production
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
